### ISSUE TITLE
Candidate branch for release v0.2.0

### ISSUE THREAD

**Issue by jwintz** [LPCIC/elpi-lang#2]
The trace visualisation and navigation has been merged into a candidate branch for the next release.

Before requesting a merge into `master`, subsequent developments will happen here.

This issue will help track issues and tasks remaining when archiving the proof of concept original repository.

NOTE: Syntax highlighting tested and working fine with no regression.

## Issues

- [ ] `hopTo`: When watching for a generated trace, whenever the transitional file changes, the trace is updated, which includes file locations, of course. If the elpi source file from which the trace originates is not the current buffer in VSCode, file location links do not work.
  - [ ] Add safe guards at the least
  - [ ] Either the trace keeps tracks of the original elpi/elpi-coq source file
  - [ ] Either assumptions should be made
    - [ ] ?
    - [ ] ?

## TODO

- [x] Code fragments syntax coloring - best option seems to use `shiki` and link vs code variables in shiki's `css-variables` them, believe it or not, vscode provides no API over its syntax highlighting engine. 
  - [x] Format `*_text` exhaustively
- [ ] Propose a design or heurstics so that LHS & RHS folding for subcards gets intuitive and (semi ?) automatic
  - [ ] Link toggles between LHS, RHS
- [x] Design the settings for this extension
  - [x] ~~Investigate the link with `ocaml-platform` VSCode extension~~ Doesn't build at the moment of writing
  - [x] Settings contribution point: declare and retrieve
  - [x] Binaries location
    - [x] `elpi`
    - [x] `elpi-trace-elaborator`
- [x] M$ Windows compatibility & testing, use node process piping for that
- [x] Illustrate `README.md` with screenshots and screencasts
- [ ] Publication facility

**Comment by jwintz** [comment]
On `M$ Windows compat`.

From https://opam.ocaml.org/doc/Install.html#Windows:

> Full support for Windows is planned for opam 2.2, and we expect to provide an opam package in [Chocolatey](https://chocolatey.org/) and [winget](https://docs.microsoft.com/en-us/windows/package-manager/). If you'd like to help out, please get in touch!

After a bit of digging, it seems that any current attempt (coq-platform or https://github.com/fdopen/opam-repository-mingw/releases) relies on an underlying linux stack, either cygwin or mingw. However, with the advent of WSL2, these requirements may not hold over time.

Here is a Windows test of the extension, using VSCode's Remote WSL connector and everything works fine.

A real windows port would assume have "native" builds of `elpi` and its binaries.

To be discussed.

![Screenshot 2022-06-23 123002](https://user-images.githubusercontent.com/3277054/175279966-17eeda77-03e0-49bc-bb5b-2f01a6760162.png)

**Comment by jwintz** [comment]
On "Elpi Settings".

VSCode API is very straight forward when it comes to settings. Contribution entry points are easily declared in the main `package.json`, the extension source code retrieves them easily.

Next step is to infer binaries location, but requires more discussion, should it be implemented in a cross platform way, see previous comment for that.

![Screenshot 2022-06-23 122820](https://user-images.githubusercontent.com/3277054/175280411-e76038c5-1cf0-4116-ba36-1bf52ed74503.png)

**Comment by gares** [comment]
Nice, we have to discuss which options are there. E.g. dune is useful in our tests because it builds and exec automatically, but if elpi is installed system wide, then one should not use dune at all. I agree elpi and elpi-trace-elaborator have to have an option. I don't get what the opam root is for, actually.

**Comment by gares** [comment]
OT, the visual improvements look great!
